# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_LTbEyRTWpo70bIVNso2xLNWDEiH6Fa
"""

k = int(input())
if k==1 or k%4==0:
  print("YES")
else:
  print("NO")