# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_LTbEyRTWpo70bIVNso2xLNWDEiH6Fa
"""

x1 = int(input())
y1 = int(input())
x2 = int(input())
y2 = int(input())
if abs(x1-x2) == abs(y1-y2):
  print("YES")
else:
  print("NO")