# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_LTbEyRTWpo70bIVNso2xLNWDEiH6Fa
"""

x1 = int(input())
y1 = int(input())
x2 = int(input())
y2 = int(input())
dx = int(input())
dy = int(input())
if dx ==1 and dy==2 or dx==2 and dy==1:
  print("YES")
else:
  print("NO")